// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-debug.fsx"
#load "../AssemblyInfo.fs"
      "../src/Definition.fs"
      "../src/StringConversion.fs"
      "../src/Evaluation.fs"
      "../src/Printer.fs"
      "../src/TypeInference.fs"
      "../src/Compiler.fs"
      "../src/compiledStdlib.fs"
      "../src/stdlib.fs"
      "../src/Parser.fs"
      "../tests/EvaluationTests.fs"
      "../tests/TypeInferenceTests.fs"
      "../tests/stdlibTests.fs"
      "../tests/ExternalParserTests.fs"
      "../Program.fs"
